config/routes.rb
Rails.application.routes.draw do

  resources :likes, only: [:create, :destroy]
  
  get 'users/show'

  root 'pages#home'
  get 'pages/faq', as: :faq
  get 'pages/home', as: :home
  get 'pages/contact', as: :contact

  devise_for :users
  get 'everyone' => 'users#index', as: :everyone
  get ':id' => 'users#show', as: :user

  put 'challenges/update_days', as: :update_days
  put 'challenges/reset_days', as: :reset_days
  put 'challenges/reset_entered', as: :reset_entered
  resources :challenges

  resources :comments, only: [:create, :edit, :update, :destroy]

  
  

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	include PublicActivity::Common
	# tracked except: :update, owner: ->(controller, model) { controller and controller.current_user }

	belongs_to :user

	def self.reset_entered
		@challenges = self.all

		@challenges.each do |challenge|
			challenge.update_attribute(:entered, false)
		end
	end

	def self.reset_entered_america
		@challenges = self.all

		@challenges.each do |challenge|
			challenge.update_attribute(:entered, false)
		end
	end

	def self.reset_entered_europe
		@challenges = self.all

		@challenges.each do |challenge|
			challenge.update_attribute(:entered, false)
		end
	end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_challenge, only: [:show, :edit, :update, :destroy]
	before_action :verify_access_to_challenge, only: [:edit, :destroy]

	# GET /challenges
	# GET /challenges.json
	def index
		@challenges = current_user.challenges
	end

	# GET /challenges/1
	# GET /challenges/1.json
	def show
	end

	# GET /challenges/new
	def new
		@challenge = current_user.challenges.build
	end

	# GET /challenges/1/edit
	def edit
	end

	# POST /challenges
	# POST /challenges.json
	def create
		@challenge = current_user.challenges.build(challenge_params)

		respond_to do |format|
			if @challenge.save
				@challenge.create_activity :create, owner: current_user, challenge_day: 0
				format.html { redirect_to root_path }
			else
				format.html { render :new }
			end
		end
	end

	# PATCH/PUT /challenges/1
	# PATCH/PUT /challenges/1.json
	def update
		respond_to do |format|
			if @challenge.update(challenge_params)
				# @challenge.create_activity :update, owner: current_user, challenge_day: @challenge.day

				format.html { redirect_to root_path }
			else
				format.html { render :edit }
			end
		end
	end

	def update_days
		@challenge = current_user.challenges.last	
		if Rails.env.development? || !@challenge.entered? 
			if @challenge.update(day: @challenge.day + 1, entered: true)
				if @challenge.day == 21
					@challenge.create_activity :reached_day_21, owner: current_user, challenge_day: @challenge.day, message: params[:message]
				else
					@challenge.create_activity :update_days, owner: current_user, challenge_day: @challenge.day, message: params[:message]
				end
			end
		end												 
	end

	def reset_days
		@challenge = current_user.challenges.last
		if Rails.env.development? || !@challenge.entered? 
			if @challenge.update(day: 0, entered: true)
				@challenge.create_activity :reset_days, owner: current_user, challenge_day: @challenge.day, message: params[:message]
			end
		end
	end

	def reset_entered
		@challenge = current_user.challenges.last
		@challenge.update_attribute(:entered, false)
		# TODO(Max): Undo changing day count
		redirect_to root_path
	end

	# DELETE /challenges/1
	# DELETE /challenges/1.json
	def destroy
		if @challenge.destroy
			@challenge.create_activity :destroy, owner: current_user, challenge_day: @challenge.day, message: params[:message]
			respond_to do |format|
				format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
			end
		else
			respond_to do |format|
				format.html { redirect_to challenges_url, error: 'A problem occurred. Please try again.' }
			end
		end

	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_challenge
			@challenge = Challenge.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def challenge_params
			params.require(:challenge).permit(:name, :day, :reason, :user_id, :entered)
		end

		def verify_access_to_challenge
			if current_user.id != @challenge.user_id
		      flash[:alert] = "You don't have access to edit that challenge."
		      redirect_to root_path
		      return
	    	end
		end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :reason %><br>
    <%= f.text_field :reason, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
	<h4>Editing challenge</h4>
  </div>

<%= render 'form' %>
	
	<div class="centered link-end-form">
		<p>Or, if you want to forfeit this challenge and <%= link_to "start a new one", new_challenge_path %>.</p>
	</div>
</div>

app/views/challenges/index.html.erb
<section id="my-challenges">
  <div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>My Challenges</h1>

        <table>
          <thead>
            <tr>
              <th>Challenge</th>
              <th>Days</th>
              <th>User</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @challenges.each do |challenge| %>
              <tr>
                <td><%= challenge.name %></td>
                <td><%= challenge.day %></td>
                <td><%= link_to 'Show', challenge %></td>
                <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
                <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Challenge', new_challenge_path %>
    </div>
  </div>
</section>

app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/reset_days.js.erb
// update day count
$("#day").html('<%=escape_javascript @challenge.day.to_s %>');
// change buttons for 'change your mind'
$('.complete-or-fail').html('<%= j render "layouts/changed_your_mind" %>');
// Prepend the activity to the feed
$("#activity-list").prepend('<%= j render_activity Activity.last %>'); // TODO(Max): change this method to return the last activity FOR THE CURRENT USER

app/views/challenges/reset_entered.js.erb
$('.complete-or-fail').html('<%= link_to "Done", "#", remote: true, class: "button complete", id: "link-complete" %><%= link_to "Fail", "#", remote: true, class: "button fail", id: "link-fail" %>');

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
  	<h4><%= @challenge.name %></h4>
  </div>
  <div class="panel-body">
	<p>
	  <strong>Day:</strong>
	  <%= @challenge.day %>
	</p>
	<p>
	  <strong>Reason:</strong>
	  <%= @challenge.reason %>
	</p>

	<p>
	  <strong>Who?</strong>
	  <%= @challenge.user.name %>
	</p>
	<% if current_user.id == @challenge.user_id %>
	<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
	<% end %>
	<%= link_to 'Back', challenges_path %>
  </div>
</div>

app/views/challenges/update_days.js.erb
<% if @challenge.day < 21 %>
	// update day count
	$("#day").html('<%= j @challenge.day.to_s %>');
	// change buttons for 'change your mind'
	$('.complete-or-fail').html('<%= j render "layouts/changed_your_mind" %>');
	// Prepend the activity to the feed
	$("#activity-list").prepend('<%= j render_activity Activity.last %>'); // TODO(Max): change this method to return the last activity FOR THE CURRENT USER
<% elsif @challenge.day == 21 %>
	// TODO(Max): change to something celebration etc.
	$("#activity-list").prepend('<%= j render_activity Activity.last %>'); // TODO(Max): change this method to return the last activity FOR THE CURRENT USER
	$("#sidebar-challenge").html('<p class="challenge-info challenge-info-reason">You have reached Day 21. Congratulations on keeping your word. You have proved character, determination, and true grit. Check your email for a small, but meaningful, surprise!</p>');
	// Display new challenge form
	$("#sidebar-challenge").append('<%= j render "layouts/new_challenge", challenge: Challenge.new %>');
<% end %>