config/routes.rb
Rails.application.routes.draw do

  resources :likes, only: [:create, :destroy]
  
  get 'users/show'

  root 'pages#home'
  get 'pages/faq', as: :faq
  get 'pages/home', as: :home
  get 'pages/contact', as: :contact

  devise_for :users
  get 'everyone' => 'users#index', as: :everyone
  get ':id' => 'users#show', as: :user

  put 'challenges/update_days', as: :update_days
  put 'challenges/reset_days', as: :reset_days
  put 'challenges/reset_entered', as: :reset_entered
  resources :challenges

  resources :comments, only: [:create, :edit, :update, :destroy]

  
  

end

app/views/layouts/_activities.html.erb
<% @activities.each do |activity| %>
	<%= render_activity activity %>
<% end %>

app/views/layouts/_activity_footer.html.erb
<div class="activity-footer">
	<div class="row">
		<div id="like-container-<%= activity.id %>" class="likes-container">
			<%= render 'layouts/likes', activity: activity %>
		</div>
		<div id="like-form-<%= activity.id %>" class="icon">
			<%= render 'layouts/like_form', activity: activity %>
		</div>
		<%= link_to (image_tag "comment-gray.png", class: "comment-img"), "", class: "comment-bubble icon" %>
	</div>
</div>

app/views/layouts/_changed_your_mind.html.erb
<p style="margin-top: 18px;">You have already logged your status for today.</p><p> Give some encouragement to someone who might be struggling with their challenge. Have a wonderful day!</p>

<!-- <p style="margin-top: 18px;">You have already logged your status for today.</p> <%= link_to "Changed your mind?", reset_entered_path, method: :put, class: "changed-your-mind" %> -->

app/views/layouts/_comment_form.html.erb
<div class="add-comment">
	<div class="row">
		<%= simple_form_for Comment.new, url: comments_path, method: 'post', remote: true do |f| %>
				<%= f.input :comment, as: :string, input_html: { class: "form-control" }, label: false, placeholder: "Write a comment..." %> 
				<%= f.input :commentable_id, as: :hidden, input_html: { value: activity.id } %> 
				<%= f.submit "Comment", class: "button button-secondary button-form" %> 
		<% end %>
	</div>
</div> <!-- end add-comment -->

app/views/layouts/_comments.html.erb
<div class="comments-container">
	<ul id="comment-list-<%= activity.id %>" class="comment-list">
		<% activity.comments.each do |comment| %>
			<li class="comment" id="comment-<%= comment.id %>">
				<%= image_tag comment.user.profile_pic, class: "img-circle" %>
				<span class="comment-name"><%= comment.user.name if comment.user %>:</span> <span class="comment-comment"><%= auto_link(comment.comment) %></span>
				<% if comment.user == current_user %>
						<span class="edit-delete">
							<%= link_to "edit", edit_comment_path(comment), remote: true, class: "Edit" %>
							<%= link_to icon('trash'), comment, method: :delete, class: "image-delete", remote: true, data: { confirm: 'Are you sure you want to delete this comment?' } %>
						</span>
				<% end %>
			</li>
		<% end %>
	</ul>
</div>

app/views/layouts/_feed.html.erb
	<div id="page-content-wrapper" class="feed">
		<div class="container-fluid">
			<div class="row">
				<a class="hamburger-menu visible-xs" href="#menu-toggle" id="menu-toggle">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<div class="col-lg-12 feed-container">
					<ul id="activity-list">
						<%= render 'layouts/activities' %>
					</ul>
					<%= will_paginate @activities %>
				</div>
			</div>
		</div>
	</div>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46643953-2', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_like.html.erb
<div id="like-form-<%= activity.id %>">
	<%= render 'layouts/like_form', activity: activity %>
</div>

app/views/layouts/_like_form.html.erb
<% if current_user %>
	<div class="like-button">
		<% if current_user.likes?(activity) %>
			<%= render 'likes/unlike', activity: activity %>
		<% else %>
			<%= render 'likes/like', activity: activity %>
		<% end %>
	</div>
<% end %>

app/views/layouts/_likes.html.erb
<% if activity.likes.count > 0 %>
		<ul class="likes">
			<% activity.likes.each do |like| %>
				<li class="like" data-toggle="tooltip" title='<%= like.user.name %>'><%= image_tag like.user.profile_pic, class: "img-circle" %></li>
			<% end %>
			<% if activity.likes.count == 1 %>
				likes this.
			<% else %>
				like this.
			<% end %>
		</ul>
<% end %>

app/views/layouts/_my_challenge.html.erb

<!-- Sidebar -->
<div id="sidebar-wrapper">
		<a class="hamburger-menu hamburger-menu-white visible-xs" href="#menu-toggle2" id="menu-untoggle">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
	<div class="sidebar-content">
		<div id="sidebar-challenge">
			<% if @current_challenge.nil? %>
				<%= render 'layouts/new_challenge', challenge: @challenge %>
			<% else %>
				<span id="day"><%= @current_challenge.day %></span>
				<div class="complete-or-fail">
					<% if @current_challenge.entered? %>
						<%= render 'layouts/changed_your_mind', challenge: @challenge %>
					<% else %>
						<%= link_to "Done", "#", remote: true, class: "button complete", id: "link-complete" %>
						<%= link_to "Fail", "#", remote: true, class: "button fail", id: "link-fail" %>
					<% end %>
				</div>

				<p class="challenge-info-title">My Challenge</p>
				<p class="challenge-info challenge-info-name"><%= @current_challenge.name %></p>
				<p class="challenge-info-title">Reason</p>
				<p class="challenge-info challenge-info-reason"><%= @current_challenge.reason %></p>

			<% end %>
		</div>

		<div class="sidebar-nav">
			<%= link_to "My Profile", user_path(current_user) %>
			<%= link_to "Settings", edit_user_registration_path %>
			<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
			<%= link_to raw("Created by Junto Studio") + image_tag("jslogo.png", class: "jslogo"), "http://www.juntostudio.com", class: "created-by-js" %>
		</div>

	</div> <!-- sidebar content -->
	</div> <!-- /#sidebar-wrapper -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	  <span class="sr-only">Toggle navigation</span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	</button>
	<%= link_to "21", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse">
	<ul class="nav navbar-nav navbar-right">
	  <% if user_signed_in? %>
		  <li><%= link_to "My Profile", user_path(current_user) %></li>
		  <li><%= link_to "Settings", edit_user_registration_path %></li>

		  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
	  <% else %>
	  	  <li><%= link_to "FAQs", faq_path %></li>
		  <li><%= link_to "Sign In", new_user_session_path %></li>
		  <li><%= link_to "Sign Up", new_user_registration_path %></li>
	  <% end %>
	</ul>
  </div><!-- /.navbar-collapse -->

  </div><!-- /.container --> 
</nav>

app/views/layouts/_new_challenge.html.erb
<p class="challenge-info">Start a New Challenge</p>
    <%= form_for challenge do |f| %>
    <%= image_tag "logo.png", class: "logo" %>
    <p class="challenge-info-title">My Challenge</p>
    <div class="form-group">
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <p class="challenge-info-title">Reason</p>
    <div class="form-group">
        <%= f.text_field :reason, class: "form-control" %>
    </div>
    <%= f.hidden_field :user_id %>
    <%= f.submit "Start Now", class: "button button-primary", style: "margin-left: 20px;" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twentyone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- for Google -->
	<meta name="description" content="" />
	<meta name="keywords" content="" />

	<meta name="author" content="www.juntostudio.com" />
	<meta name="application-name" content="" />

	<!-- for Facebook -->          
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:description" content="" />
</head>
<body>

	<%= render 'layouts/navbar' unless @no_navbar.present? %>
	
	<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
	<% elsif alert %>
	    <p class="alert alert-danger"><%= alert %></p>
	<% end %>

<%= yield %>

	<%= render 'layouts/google_analytics' %>
	
</body>
</html>